[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rephraser"
version = "0.0.1"
description = "Rephrase essays and collage texts"
readme = "README.md"
authors = [{ name = "EliazarInso", email = "deadbush225@gmail.com" }]
license = { file = "LICENSE.txt" }
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: End Users/Desktop",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Text Editors",
    "Topic :: Text Processing",
]
keywords = ["rewrite", "text", "rephrase"]
dependencies = ["PyQt5 >= 5.15.10"]
requires-python = ">=3.9"

# [project.optional-dependencies]
# dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]
Homepage = "https://github.com/Deadbush225/RePhrase"

[project.scripts]
rephraser = "rephraser.__main__:main"

# This is configuration specific to the `setuptools` build backend.
# If you are using a different build backend, you will need to change this.

# If there are data files included in your packages that need to be
# installed, specify them here.
[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
rephraser = ["*.png", "*.qss", "images/*"]